### ISSUE TITLE
🔴🔴🔴 Production crashed: Bootsnap error - config

### ISSUE THREAD

**Issue by Danrod16** [Danrod16/equinox_admin#133]
Heroku logs: 

`022-12-22T17:07:27.480058+00:00 app[web.1]: from bin/rails:9:in `<main>'
2022-12-22T17:07:27.626214+00:00 heroku[web.1]: Process exited with status 1
2022-12-22T17:07:27.686568+00:00 heroku[web.1]: State changed from starting to crashed
2022-12-22T17:07:48.679524+00:00 app[api]: Deploy a23368c8 by user daniel.rod93@gmail.com
2022-12-22T17:07:48.679524+00:00 app[api]: Release v72 created by user daniel.rod93@gmail.com
2022-12-22T17:07:50.072212+00:00 heroku[web.1]: State changed from crashed to starting
2022-12-22T17:07:58.300148+00:00 heroku[web.1]: Starting process with command `bin/rails server -p ${PORT:-5000} -e production`
2022-12-22T17:08:01.504417+00:00 app[web.1]: => Booting Puma
2022-12-22T17:08:01.504442+00:00 app[web.1]: => Rails 6.0.6 application starting in production
2022-12-22T17:08:01.504442+00:00 app[web.1]: => Run `rails server --help` for more startup options
2022-12-22T17:08:02.413684+00:00 app[web.1]: Exiting
2022-12-22T17:08:02.419993+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- JSON (LoadError)
2022-12-22T17:08:02.419995+00:00 app[web.1]: Did you mean?  json
2022-12-22T17:08:02.419999+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
2022-12-22T17:08:02.420000+00:00 app[web.1]: from /app/app/services/subdomain_creator.rb:3:in `<main>'
2022-12-22T17:08:02.420004+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2022-12-22T17:08:02.420004+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2022-12-22T17:08:02.420006+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
2022-12-22T17:08:02.420009+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
2022-12-22T17:08:02.420011+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
2022-12-22T17:08:02.420020+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
2022-12-22T17:08:02.420020+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
2022-12-22T17:08:02.420022+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
2022-12-22T17:08:02.420029+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
2022-12-22T17:08:02.420030+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
2022-12-22T17:08:02.420032+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
2022-12-22T17:08:02.420039+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
2022-12-22T17:08:02.420041+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
2022-12-22T17:08:02.420043+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
2022-12-22T17:08:02.420054+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
2022-12-22T17:08:02.420054+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
2022-12-22T17:08:02.420061+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
2022-12-22T17:08:02.420061+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
2022-12-22T17:08:02.420068+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/railties-6.0.6/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'`

Probably some errors with versioning of ruby and the gems. I will try to investigate, if you have any idea also @christinasugiono  ? 🤔

**Comment by christinasugiono** [comment]
@Danrod16 I think now it's working!

I changed `require 'JSON'` to `require 'json'` in the subdomain_creator.rb line 3
